/*
 * CSCI 363 Computer Networks
 * Lab 10: Working with Ethernet Packet Traces
 *
 * Skeleton file for lab exercise.
 *
 * This is a skeleton program for analyzing Ethernet packet traces
 * generated by 'wireshark'.
 *
 */

#include <stdlib.h>
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>
#include <sys/socket.h>
#include <net/if.h>
#include <netinet/in.h>
#include <netinet/if_ether.h>
#include <time.h>
#include <pcap.h>

#define MAX_ETH_FRAME_LEN xxx  // maximum Ethernet frame length

int main(int argc, char* argv[]){
	
	if(argc < 1) {
		printf("Improper usage: %s [ packet capture ]\n", argv[0]);
		exit(1);
	}

	/* define local variables */

	pcap_t *p;
	char errbuf[PCAP_ERRBUF_SIZE];

	p = pcap_open_offline(argv[1], errbuf);

	/* process file header */

	printf("==== GLOBAL HEADER ====\n");
	printf("host order is %s \n", pcap_is_swapped(p) ? "in order" : "out of order" );
	printf("major version %d\n", pcap_major_version(p));
	printf("minor version %d\n", pcap_minor_version(p));
	//printf("maximum captured packet length %ld\n", pcap_  snaplen);
	printf("link layer type %d\n", pcap_datalink(p));

	/*
	 * while there are tuples to read
	 *     read one frame header
 	 *     read corresponding frame
	 *     extract Ethernet addresses, IP addresses and protocol type
	 *     print information extracted
	 * end-while
	 *
	 */

	struct pcap_pkthdr *hdr;
	const u_char *data;

	int i = 0;

	while(pcap_next_ex(p, &hdr, &data) == 1) {
	printf("packet %d\n", i);
	i++;
	}	
	pcap_close(p);
	return 1;
}
